### ISSUE TITLE
Feedback is posted to wrong commit

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#107]
Feedback was requested on: https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T1/d0_w8j0b/commit/a66dce8464958a4788d3497acfbf4a552a90747d

But was given on: https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T1/d0_w8j0b/commit/4fed933193aae684d7c921844d2ea766550f47b9

**Comment by rtholmes** [comment]
This one is confusing because the 'given on' thread also has requests so we'll never be able to sort out what exactly happened there.

**Comment by rtholmes** [comment]
Added a bunch of logging; hopefully it will help diagnosing this next time.

**Comment by rtholmes** [comment]
Fixed and deployed
