### ISSUE TITLE
AutoTest counts Internal Error as a run

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#115]
>my CSID is XXXXX and on one of my recent commits (cd3c2b5), autobot returned this comment to me: Internal error: The grading service failed to handle the request. after making a few more fixes, i called autobot again on another commit (409c2b7) and autobot tells me that i must wait 11 hours. if i wasn't shown a grade due to an internal error, why do i have to wait 11 hours? shouldn't this not count as a valid autobot call?

**Comment by rtholmes** [comment]
@nickbradley for that execution `postbackOnComplete: false` but `state: 'FAIL'`. I think if the grader is able to assign `FAIL` it should set `postbackOnComplete: true`?
