### ISSUE TITLE
Grader logging updates

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#123]
High-level list of logging notes about grader & autotest; will be updated as encountered. 

- [x] If there is any way to decrease the verbosity of logging on the `db` container it would be great!
- [x] Grader should log at `Info` level, not `Trace` in production (how we do this on other containers isn't great and we should revisit this more correctly; maybe through the `.env`?)
- [x] `grader      | <W> 2018-10-3 18:29:23: GradeTask::execute() - Failed to checkout commit. Requested: c40c9c91bbf7edd69f46f6f786eee35f9e421c77 Actual: c40c9c91bbf7edd69f46f6f786eee35f9e421c77
grader      | . Continuing to grade but results will likelybe wrong.` (these SHAs seem to match so the message probably isn't right)
- [x] ` <T> 2018-10-3 18:31:56: GradeTask::execute() - Start grading container 6a4348` should be info, not trace
- [x] ` <T> 2018-10-3 18:31:39: GradeTask::execute() - Container f29b9b exited with code 0.` should be info, not trace
- [x] `<T> 2018-10-3 18:31:39: GradeTask::execute() - Remove container undefined` is this a bug (undefined) or should it be logged as an error?
- [x] `<W> 2018-10-2 10:15:13: AutoTest::invokeContainer(..) - ERROR for SHA: acf10243e0ee7cbfe5d54a4f8e09882ef417c2fa; ERROR with grading service: RequestError: Error: ESOCKETTIMEDOUT` This is actually in AutoTest, but should be treated more like an info than a warning (and without the ERROR text all over the place)

**Comment by rtholmes** [comment]
(feel free to just update these on master so they get deployed along with any other small updates)

**Comment by nickbradley** [comment]
Do you want only the Grader to log at `INFO`? The easy way to do this is to just set `LOG_LEVEL=INFO` somewhere (could be in the .env for all services, or just in the compose settings for Grader).

**Comment by nickbradley** [comment]
For the `db` we can try setting the [`--quiet`](https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-quiet) option by setting the [entrypoint configuration](https://github.com/docker-library/docs/blob/master/mongo/README.md#customize-configuration-without-configuration-file) on the mongo container.

**Comment by nickbradley** [comment]
@rtholmes thoughts on https://github.com/ubccpsc/classy/issues/123#issuecomment-427532539? (I'll just merge the first two points to master; last one will probably become its own issue).

**Comment by rtholmes** [comment]
I think your idea of doing it in .env for all services is the way to go!

**Comment by rtholmes** [comment]
Fixed.
