### ISSUE TITLE
Grades no longer being displayed in portal

### ISSUE THREAD

**Issue by ccunnin8** [ubccpsc/classy#127]
Grade for D0 remains but, grades for D1 and D2 are no longer displayed.

**Comment by rtholmes** [comment]
Thanks for the report @ccunnin8 ; could you do a hard refresh and see if it is working now?

**Comment by ccunnin8** [comment]
Working! Thanks

Could you by any chance send me logs for the last submission I did for d2.

Commit: 9447abc. 

Autobot says 7 pass 5 fails 0 skip, are there really only 12 tests for d2?

**Comment by rtholmes** [comment]
@ccunnin8 there are only 12 dataset tests but all of the query tests are failing; we're seeing this on our side originating from your code:

`<AT_E> Object: 2018-10-6 08:58:49: MAJOR PROBLEM (probably): AutoTest caught an unhandled rejection (promise: [object Promise], `

**Comment by ccunnin8** [comment]
Thank you

**Comment by ccunnin8** [comment]
Could you look at the logs for commit ca623bc961f3e224a8fd7036a695488629548ab7.

I am still receiving a 30%, but I am confident that I am handling every rejection.

I don't understand and it's driving me crazy!

Thanks,
Corey Cunningham

On Oct 06, 2018, at 01:53 PM, Reid Holmes <notifications@github.com> wrote:

@ccunnin8 there are only 12 dataset tests but all of the query tests are failing; we're seeing this on our side originating from your code:
<AT_E> Object: 2018-10-6 08:58:49: MAJOR PROBLEM (probably): AutoTest caught an unhandled rejection (promise: [object Promise],
