### ISSUE TITLE
Admin: Should be able to view, create, and edit deliverables

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#13]
Major tasks:

- [x] Admin should be able to edit a deliverable.
- [x] Admin should be able to create a deliverable.
- [x] Admin & staff should be able to view deliverables.
- [x] Admin should be able to specify the current default deliverable for AutoTest.

**Comment by jopika** [comment]
Ack, I never saw this.

I think I intend to extend the page with the Schema to be able to add the rubrics as needed.
