### ISSUE TITLE
is ubcbot/autotest working correctly?

### ISSUE THREAD

**Issue by ccunnin8** [ubccpsc/classy#133]
I am unable to increase my grade above a 30%.

I cannot find any unhandled errors, all promises with a then have a catch, all awaits are in a try catch block.

Please help! 

Thanks.

**Comment by rtholmes** [comment]
Yes, autotest is working. This is not the right place for support on your tests though. I would clone your repo and try running the tests there. The first time you do it nothing will work, because your implementation depends on local state the autotest server won't have.

**Comment by ccunnin8** [comment]
Can you look at the logs for commit: 3b2f7815bcc4086e6971a1abb5a47f42338d0e90 and help me figure out why I am not getting "Container did not complete on time"? Thanks, Corey
