### ISSUE TITLE
VM running out of space periodically

### ISSUE THREAD

**Issue by mgelbart** [ubccpsc/classy#142]
This has happened a few times ago. The output of `df -h` is

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        36G   36G   20K 100% /
...
```

Then I run

```
docker-compose --file docker-compose.340.yml down
docker-compose --file docker-compose.340.yml up -d
```

and suddenly the space is free; `df -h` gives 

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        36G   17G   19G  47% /
```

This seems to be a separate issue from the docker images themselves clogging up the image, which I address using `docker image ls` and `docker image rm`. This happens slowly over time even if I'm not building new images.

@nickbradley what sort of files does `docker-compose --file docker-compose.340.yml down` delete? I was thinking maybe Classy is cloning repos into some temp directory - could that be something it cleans up.

Is this not happening for CPSC 310?

**Comment by nickbradley** [comment]
We've also been having space issues but mostly due to repeated deployments caching intermediate images. Since you mentioned that you're cleaning up the images, it is probably that classy is storing repos in `/tmp` as you said. We fixed this in https://github.com/ubccpsc/classy/commit/42f67c58299a4bd373ead95f4b809300b6c09a1a. You can check the size of `/tmp` by running `docker exec portal ls -lh /`.

**Comment by mgelbart** [comment]
Got it, thanks for the info. I'll just deal with this manually for the meantime then, and after the semester is over we'll merge back in with the main branch, thus benefitting from your fix. 

Next time it runs out of space I'll try to remember to verify the hypothesis that it's `/tmp`.

**Comment by rtholmes** [comment]
You still need to clear these manually if you build the containers lots of times, but most other stale containers are cleaned up with a script Nick added and runs automatically within the docker-compose.
