### ISSUE TITLE
Add an endpoint to dump all results for a deliverable

### ISSUE THREAD

**Issue by aahung** [ubccpsc/classy#144]
Right now `/portal/admin/dashboard/[deliverable]/any` outputs 1000 records at max. It is handy to have a variant to outputs ALL results by specifying some parameter.

e.g., `/portal/admin/dashboard/[deliverable]/any?all=true`

or a new endpoint `/portal/admin/dashboard/[deliverable]/all`

**Comment by rtholmes** [comment]
Just closing this for now since we made do with what exists, but we can reopen if needed in future.
