### ISSUE TITLE
D3 Pull Request Doesn't Work

### ISSUE THREAD

**Issue by ccunnin8** [ubccpsc/classy#146]
When you click on the the button to create the pull request for D3 a pull request isn't initiated, it acts like it's initiating the request (screen grays out, says will take < 10 seconds) but after it's done there's no pull request on GitHub.

**Comment by rtholmes** [comment]
This is a known problem. We will issue the PR manually so you can keep going!

**Comment by ccunnin8** [comment]
Thanks

**Comment by ataraxie** [comment]
Pull request has been created. Good luck with D3!
