### ISSUE TITLE
Automate Pull Request Mechanism

### ISSUE THREAD

**Issue by ataraxie** [ubccpsc/classy#147]
Background:
- Whenever SDMM participants want to advance to D3 the click a button and expect a PR
- Currently this PR is created manually

Definition of done:
- PR is created automatically when button is clicked

Proposal:
- We continue to maintain PRs the way we do now in the [repoPatchTool repo](https://github.ubc.ca/cpsc310/repoPatchTool)
- Create (Ruby-capable) web service with endpoint `createPullRequest(github_url, pullrequest_id)`
- `pullrequest_id` must match the folder name of the PR in repoPatchTool repo (in the `patches` dir)
- Web service will pull the repoPatchTool repo, execute the ruby commands `createPatch {patch_id} apply` and `createPatch {patch_id} pullrequest`

**Comment by ataraxie** [comment]
@nickbradley @rtholmes - I wrote a small proposal down on how to automate the PRs.

**Comment by nickbradley** [comment]
Looks good. The PR service will need to be Dockerized for deployment--we can discuss how that would be done.

**Comment by ataraxie** [comment]
You should only need a container with Ruby >= 2.4 and a Web server. I propose [Sinatra](https://github.com/sinatra/sinatra). It's a very simple Ruby Web server that I've used in the past and I loved it. It'll be nice for you to take a break from JS and dive into the world of Ruby too. You'll like it!

**Comment by ataraxie** [comment]
```
# myapp.rb
require 'sinatra'

get '/' do
  'Hello world!'
end
```
:-)

**Comment by nickbradley** [comment]
We'll also need to store the PR diffs somewhere too. Actually, if they are being committed to the repo then they can just be baked into the container although I wouldn't want to include old ones since that'll inflate the container size and we are already having problems with space. We'd either need a build param to specify which PR diffs to include or only have the required diffs in the PR directory.

**Comment by nickbradley** [comment]
You could use this [Dockerfile](https://hub.docker.com/r/erikap/ruby-sinatra/~/dockerfile/) but I'd change the base image to `ruby:2.5-alpine`.

**Comment by ataraxie** [comment]
You're right, size is a problem if we just do it the way I suggested. But I would still like to keep the patches and diffs in the repo as it is right now. How about we create a tag for each patch and just include the single patch directory?

**Comment by ataraxie** [comment]
Hmm. I guess the container would still need to pull the whole repo first, so that's not a good option.

**Comment by ataraxie** [comment]
![image](https://user-images.githubusercontent.com/1646086/47170794-cc1d7500-d2bb-11e8-882d-9f69ef37c213.png)

**Comment by ataraxie** [comment]
For each patch/diff we create a tag. Then when the web service receives a `createPullRequest(github_url, pullrequest_id)` it just clones the repo with the tag `pullrequest_id` as above and executes the Ruby commands.

**Comment by rtholmes** [comment]
@ataraxie built this in the end and @braxtonhall is working on getting it into the 310 fork (so it doesn't need to be here in master).

**Comment by ataraxie** [comment]
AWESOME
