### ISSUE TITLE
listRepos endpoint

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#156]
`GET /portal/admin/repos/:kind/:delivId/:date`

`:date` is optional
`:kind` can be `[ latest, maxScore ]` // add more here as they are identified

**Comment by jopika** [comment]
What would `maxscore` or `latest` look like? Is there multiple repositories for one assignment?

**Comment by rtholmes** [comment]
Not sure this use case is worth the effort. Marking as `wontfix` until we can better understand the need.
