### ISSUE TITLE
More advanced `/portal/admin/results/:delivId/:repoId`

### ISSUE THREAD

**Issue by aahung** [ubccpsc/classy#158]
It is helpful to add one extra parameter `:filter` to achieve some features useful for analysis (e.g. running MOSS)

=> `/portal/admin/results/:delivId/:repoId/:filter` where `:filter := highestScore| highestCover| highestTest `

- `/portal/admin/results/:delivId/:repoId/highestScore` will return, array of results with the highest score, grouped by `:delivId` and `:repoIId`
- `/portal/admin/results/:delivId/:repoId/highestCover` will return, array of results with the highest coverage, grouped by `:delivId` and `:repoIId`
- `/portal/admin/results/:delivId/:repoId/highestTest` will return, array of results with the highest test score, grouped by `:delivId` and `:repoIId`

**Comment by aahung** [comment]
Refer to #156, we can also include date filter. I feel a URL parameter might works better

`/portal/admin/results/:delivId/:repoId?scoreFilter=highestScore| highestCover|highestTest&dateFilter=[timestamp1,timestamp1]`

**Comment by rtholmes** [comment]
@aahung Just back to this now; for MOSS are the existing APIs sufficient, or what is the minimum thing you actually need to make that use case work better?

**Comment by aahung** [comment]
For MOSS, assuming the /export api works, it is sufficient, since I can do the filtering offline. I haven’t tried that /export yet. 

If we want to do this filtering server-side, we can consider this proposal.

**Comment by rtholmes** [comment]
Great, I'll mark #wontfix for now and we can come back to it later if we need to.
