### ISSUE TITLE
Display preferred name?

### ISSUE THREAD

**Issue by LucasZamprogno** [ubccpsc/classy#161]
It would be great if we could see students' preferred names in the Students tab. Many of the listed names are different than those they go by in lab.

**Comment by rtholmes** [comment]
This is an issue for help@cs. We just use what the `classlist` tool gives us.

**Comment by rtholmes** [comment]
Marking as `wontfix` for now because this will block on others and we'll get it for free when the work is done. From Anthony:

> Preferred name is not yet available in ELDAP. If it was, it would be straight forward to include it in the new students.cs classlist. We'll have to put in a request with UBC IT to get it done.
