### ISSUE TITLE
Autobot requesting cached results counts as run

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#163]
From [Piazza](https://piazza.com/class/jllqzswlx9l1jg?cid=1666)
> Not sure if this is a bug or if it is intended, but it is possible to call autobot on commits where autobot has been called previously, returning the cache, when a user is supposed to still be locked out. It then resets the countdown timer back to 12 hours.

> Discovered this when I called autobot to tell me when I could call it again in the morning.

**Comment by rtholmes** [comment]
@nickbradley any chance you can check to see if this is still the behaviour for the currently deployed 310 fork?

**Comment by nickbradley** [comment]
It appears to have been fixed: after calling the bot twice on https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T2/d0_r5t0b/commit/3a78305c544645cd4913b9ce559c2910b9371792 the timer is still correct for https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T2/d0_r5t0b/commit/644775f0b6bc8321bc899fced6a75957af2136ab.

**Comment by rtholmes** [comment]
Great, thanks. Marking closed then!
