### ISSUE TITLE
Attachments should be downloadable

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#171]
210 needs the ability to download attachments created by the grading container. Right now we have a mechanism for this for `stdio`, so we just need to generalize this approach.

One shortcoming right now is we protect this route and only let `staff|admin` access it; we might need to add a permissions block to attachments so that the grading container can control who can see an attachment. 

~~A further extension for this is whether students can request a resource without it being an official grading run (e.g., can they get the attachments for all executions or just the ones they have 'paid' for?)~~

Since these last two will require changes to the attachment interface it might be worth considering both simultaneously. Dropped 'grading run'; containers can just do this with a UUID as described below.

**Comment by rtholmes** [comment]
@pcarterubc does this seem right? We can create any other issues you need for 210 next term and add them to the v2.0 milestone as well.

**Comment by pcarterubc** [comment]
Right.  We need students to be able to view (not necessarily download) a copy of the Jacoco report that's generated by the container.  This report is copied to the output folder and the path to the root html document is included in the Attachments field of the json report.

**Comment by rtholmes** [comment]
After hearing from @pcarterubc we'll punt on the 'official grading run'. If courses don't want the attachment to be guessable they can build some kind of `UUID` into the file name to make this too hard to access (and just embed the name into a feedback report given to the student). We will still add permissions though because some guessable URLs should be admin/staff only (e.g., `stdio.txt`)

**Comment by rtholmes** [comment]
@pcarterubc This should be about ready to go. In your `feedback` field you can include links like:

`https://cs210.ugrad.cs.ubc.ca/portal/resource/SOMEID/student/PATH/FILE.html`

`SOMEID` comes from a container environment variable @nickbradley added for this purpose. 

The `/student/` is important: if you put `/student/` it can be read by students, `/staff/` by staff and admins, and `/admin/` by admins only. This just lets you use the same mechanism we will use for the `stdio` that only admins can see (e.g., if you want to format other admin-specific files for them to access).  When you write the file to disk you actually need to include the `/student/` in your path on disk (aka your file would be `/student/coverage/index.html` for your coverage report.

**Comment by pcarterubc** [comment]
OK, thanks.  Will work on the container this weekend to set this up.  

@nickbradley what is the name of the container environment variable that I use to retrieve SOMEID?

**Comment by nickbradley** [comment]
SOMEID will be passed to the container as the EXEC_ID env var.

**Comment by nickbradley** [comment]
@rtholmes Where should `stdio.txt` and `report.json` go (i.e., `/admin` or `/staff`)? I'm assuming `/staff/stdio.txt` so TAs can read it and `/admin/report.json` since no one really needs to read it. This needs to be set so Grader/AutoTest knows where to read/write those two files.

**Comment by fansuniteuser** [comment]
For 310 everything can go to `staff/` right now; we could imagine putting the reports for private tests in `admin/` but it isn't worth it for this upcoming year.

**Comment by rtholmes** [comment]
@nickbradley all reports/stdio can go in `/staff` for 310. I could imagine putting private report data in `admin/` but it isn't worth it for the upcoming year.
