### ISSUE TITLE
Container did not complete in the allotted time: Error received for D2 due to GET requests for lat/lon

### ISSUE THREAD

**Issue by pszujewski** [ubccpsc/classy#172]
This message is always received when you try to send the required GET requests as a part of D2. See this discussion for more detail: 

https://courses.edx.org/courses/course-v1:UBCx+SoftEngPrjx+1T2018/discussion/forum/i1x-UBCx-SoftEngPrjx-Capstone-2018_T1/threads/5bf7a4714fc2300a040011bc

The issue is clearly linked to the get requests. If you hardcode in the lat/lon data, AutoTest completes as expected. If you send one request per building address, Autotest fails with the  message "Container did not complete in the allotted time."

**Comment by nickbradley** [comment]
Thanks for letting us know. The problem should be resolved although we are still working with the technical staff to determine the cause. If you still run into problems, feel free to reopen the issue.
