### ISSUE TITLE
repoId:delivId:sha should be a primary key

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#173]
Having multiple results for a deliverable is confusing for storing files (e.g. differentiating a `stdio` per execution) and reasoning about a repo in the data store (do I want the first, last, max?). I propose we just overwrite any existing result with a new one that has the same `repoId : delivId : sha`. 

@nickbradley do you concur?

**Comment by nickbradley** [comment]
Are you talking about in the DB or on disk? I think it makes sense for both cases.

**Comment by rtholmes** [comment]
Makes sense to _allow_ duplicates or _disallow_ them?

**Comment by nickbradley** [comment]
To _not_ allow duplicates.

**Comment by rtholmes** [comment]
Perfect, consider it done. Will roll out with the next push (although we're stuck with it for d4).
