### ISSUE TITLE
Improve .env docs

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#18]
Create a `.env.sample` and document the fields. This will probably result in several fields being combined or simplified along the way.

**Comment by rtholmes** [comment]
@nickbradley There are a few keys in `.env.sample` I couldn't document. It would probably be good to just remove `sample.dev.env` and `sample.prod.env` as well when this issue is done.  In the commit above I got rid of many `.env` settings but am open to more you think we can combine / remove.

**Comment by nickbradley** [comment]
@rtholmes: I will add comments to docker vars. However, I would be inclined to actually remove most the vars in the file--most of them should be coming from portal (see #19). This will prevent the `.env` from accidentally being committed and would move the service logic config values out of the `.env`. I'm wondering what FRONTEND_URL and BACKEND_URL are for (are the services talking to each other?). I can give more details once classy is deployed.

**Comment by rtholmes** [comment]
Classy frontend/backend needs `FRONTEND_URL` and `BACKEND_URL` to mediate their communication. Docker can improve this, but not if we want to spin up the services independently for testing and so we can set breakpoints in the debugger, etc.

Esp. in terms of AutoTest though, we could make it so the backend provides all the config settings through and endpoint, but for now it seems easiest to just keep at least the `portal-backend` settings in the `.env` which I have pretty heavily trimmed.
