### ISSUE TITLE
Stdio not rendering

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#195]
The response is no longer returning JSON but plain-text so the following fails:

https://github.com/ubccpsc/classy/blob/4e08d79bc1fb5943aeda24356e5def16f75817ba/packages/portal/frontend/html/stdio.html#L74

@rtholmes not sure if this is related to https://github.com/ubccpsc/classy/commit/01bf262f0b416b48a44b735b2fc53d36ee59bc7e (or if it was broken from the start--although I thought I checked it after changing the endpoint).

**Comment by rtholmes** [comment]
@aahung Can you take a look at this? What's the right change for making this work again?

**Comment by aahung** [comment]
looking into it right now.

**Comment by aahung** [comment]
@rtholmes I cannot access classy anymore, can I get a temporary access to it?

**Comment by rtholmes** [comment]
@nickbradley can we test this on classy.cs or does it need to be on cs310.ugrad? Just trying to figure out the right place to try this out.

**Comment by aahung** [comment]
what is classy.cs? another website?

**Comment by aahung** [comment]
@nickbradley Does changing to `editor.setValue(stdio);` work? Do you have an example of how the `stdio` looks like?

**Comment by rtholmes** [comment]
The code that is currently deployed to cs210.ugrad works for this (e.g., https://cs210.ugrad.cs.ubc.ca/stdio.html?delivId=assign0&repoId=assign0_team999999&sha=177624b2dc1e9af2527a34f940f933523e7ece0c) Was this a 310 problem, or where was it reported?

**Comment by aahung** [comment]
Ummm I cannot access that either...

**Comment by nickbradley** [comment]
@rtholmes, @aahung sorry for the late reply! Removing `JSON.parse` fixes the problem but what changed so that this became a problem (i.e. at some point the endpoint must have been returning JSON but now is returning plain-text)? I just want to make sure this is intended. Also, is this working or does it break as well 
https://github.com/ubccpsc/classy/blob/e44676ec2901200fedcb4d21adf14e720b24055e/packages/portal/frontend/html/stdio.html#L132

@aahung are you able to log in to https://classy.cs.ubc.ca?

**Comment by nickbradley** [comment]
Actually, forget the above. I can see the JSON was coming from the old `getResult` endpoint (https://github.com/ubccpsc/classy/commit/829858af144c2322546596a941098a54a6761314#diff-72c42640b8befc22b170b0452d47262eL267). The new `resource` endpoint returns a streaming response so it is coming in as plaintext. So, just removing `JSON.parse()` should be fine.
