### ISSUE TITLE
Results page isn't rendering STATE correctly

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#196]
Reported by 210: some of the `assign0_team999999` rows should be `FAIL` not `SUCCESS`.

**Comment by rtholmes** [comment]
Need to get access to the mongo credentials, emailed Mike Sanderson.

**Comment by rtholmes** [comment]
I actually think this is working as expected. `output.state: SUCCESS` for these rows, although `output.report.result: FAIL_LINT` is being set. @nickbradley I think `output.state` is the VM state right? 

@nickbradley I wonder if we should have this:

```
if (output.state === 'SUCCESS' && typeof output.report.result !== 'undefined') {
   state = output.report.result;
````

Would that make sense?

**Comment by nickbradley** [comment]
Looks good to me!
