### ISSUE TITLE
Build output not visible with docker 18.09.0

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#198]
With Docker Engine Community v18.09.0 the following 
https://github.com/ubccpsc/classy/blob/38087681832f1033eaaf7e7d09449ad315b4c8f1/packages/autotest/src/server/RouteHandler.ts#L212
does not stream any output. This is working on Docker Engine 18.03.1-ce.

**Comment by rtholmes** [comment]
This seems to be working with current docker. Whatever version that is.
