### ISSUE TITLE
Broken links in team page

### ISSUE THREAD

**Issue by LucasZamprogno** [ubccpsc/classy#215]
Team ID links in the Teams tab link to 
`https://github.ugrad.cs.ubc.ca/orgs/CPSC310-2018W-T2/teams/project_CSID1_CSID2`
instead of
`https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T2/project_CSID1_CSID2`

**Comment by rtholmes** [comment]
This is actually a 310 bug and should go in the issue tracker here (need to enable this): https://github.com/ubccpsc310/classy
