### ISSUE TITLE
Don't provision repositories for students who have dropped the course

### ISSUE THREAD

**Issue by pcarterubc** [ubccpsc/classy#216]

**Comment by rtholmes** [comment]
Fixed and tested on classy.cs.

**Comment by pcarterubc** [comment]
Yup and saw a confirmation that 90-something students had been marked withdrawn.

**Comment by rtholmes** [comment]
Once provisioning is done, could you get us a csid or two for some students that should have been withdrawn but had repos provisioned for them?

**Comment by pcarterubc** [comment]
OK, will do.
