### ISSUE TITLE
Return list of deliverables students can form teams on

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#227]
`ConfigTransport` can do this (`/portal/config` endpoint). This will let the student UI have a dropdown for teams.

**Comment by andrewstec** [comment]
I may take a look at this issue as part of https://github.com/ubccpsc/classy/issues/341.

I believe they are related.

**Comment by andrewstec** [comment]
PR here: https://github.com/ubccpsctech/classy/pull/115.

**Comment by andrewstec** [comment]
Merged: https://github.com/ubccpsctech/classy/pull/115.
