### ISSUE TITLE
BUG: Icons not displaying in Admin Navigation Panel

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#254]
This issue was observed on UBCCPSCTECH and on the CS210 server, which entails that this bug likely exists on the Master branch of the Root Classy repo.

![image](https://user-images.githubusercontent.com/7872295/62068089-33246e80-b1ea-11e9-8251-66a59510933e.png)

**Comment by winstan** [comment]
I'm guessing something in an external dependency changed... Anybody have any ideas?

**Comment by andrewstec** [comment]
After removing the yarn lockfiles found in the project and re-building the project, it does not look like a versioning issue at this time.

This may be a CDN CSS issue, as you mentioned @winstan. If our projects are not experiencing any other bugs, perhaps we should see if this issue is resolved on its own. I have, however, not seen any new issues opened on the Onsen UI Github repository. If we want, we can continue to explore this issue and open an issue.

**Comment by andrewstec** [comment]
Onsen UI committed this change 6 hours ago: 

![image](https://user-images.githubusercontent.com/7872295/62071092-a16c2f80-b1f0-11e9-9a88-3ba9779f9ea0.png)

Might be related. Just exploring this possibility.

**Comment by rtholmes** [comment]
It is definitely a result of the last onsen update. The onsen version is actually set in the bower file, not yarn.

**Comment by andrewstec** [comment]
Unfortunately, I have been unable to find a fix in the meantime. I have found the `frontend/node_modules/onsenui/bowser.json` but have not found anything relevant to change in regard to versioning. 

![image](https://user-images.githubusercontent.com/7872295/62074117-eabf7d80-b1f6-11e9-974a-a7b61780999a.png)

I checked in the latest version of the `css/onsenui.css` code and the CSS import statements are listed first, as OnsenUI mentions they should be in the CHANGELOG.md of the 2.10.10 bump.

We may be able to downgrade Onsen UI in the package.json to get to a version where the import statements are NOT listed first in `css/onsenui.css`, but we already had a previous version of Onsen UI before attempting to update to OnsenUI v.2.10.10 to fix the issue. Both the older version and new version seems to be breaking.

I suspect OnsenUI has to make a change on their end, but I could be wrong. 

@rtholmes Perhaps you were suggesting building the Onsen UI project manually?

**Comment by rtholmes** [comment]
I was wrong about the bower thing, that was another project, sorry. I wonder if changing the onsenui version in package.json to "2.9.9" from its current more flexible version string might work. We'd have to make sure a cached version isn't installed on the local machine too.

**Comment by andrewstec** [comment]
@rtholmes The CDN 2.10.8 works. If we lock-down the version of `onsenui.css` in the front-end portal index.html, the application works. 

This is likely a CDN issue because of the release that Onsen UI did. I have asked Onsen UI to re-open the issue because it appears that their fix did not work. I could be wrong, but we will see what happens. 

We can either lock-down the version or wait for Onsen UI to, perhaps, fix their issue.

**Comment by rtholmes** [comment]
Great work! For now let's just lock down the version to 2.10.8 and see how it shakes out on their end at the end of the fall term.

**Comment by winstan** [comment]
Stop-gap done for cs210:

docker exec -it classy_portal sh
vi /app/packages/portal/frontend/html/index.html
change /onsenui/ -> /onsenui@2.10.8/

I'd rather see if 2 (or so) weeks is enough for onsen to get it fixed...

**Comment by winstan** [comment]
Fixed in https://github.com/ubccpsc/classy/commit/b8678886c0c3eca0c9575b14bcf96b0f90a4f6ca
