### ISSUE TITLE
Nice to Have: Organization Setup Automation

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#256]
Github organizations require some configuration work for each class to setup. Ideally, we could create these Github organizations automatically through the API.

Additionally, the 'classytest' organization that we use on Github.com has a state that we may need to deconstruct if we want to drop/repair/create a new testing organization due to unexpected issues or on a different Github server.

Nice to Have's:

- Test environment requires some documentation or automation to drop/create
- Be able to add main team groups, such as 'staff', 'admin', with appropriate staff.

**Comment by andrewstec** [comment]
This is not a true issue, but a task we may decide to develop when we have more time.

**Comment by winstan** [comment]
There are a handful of python scripts that we use for doing this. They're not finished, nor are they anywhere really official yet.

**Comment by andrewstec** [comment]
Sounds great. We can hopefully concentrate on improving those soon. It would be great to automate the Github organization setup and some of the other pre-requisites.

**Comment by andrewstec** [comment]
https://github.com/ubccpsctech/classy_maintenance_util can mostly setup an organization right now. It still requires manual effort to setup the OAuth Application and some of the organization default repo/team permissions.
