### ISSUE TITLE
default circleCI env is broken

### ISSUE THREAD

**Issue by winstan** [ubccpsc/classy#268]
User parameterization included recently has broken the .env circleCI uses by default for github.com

**Comment by winstan** [comment]
It's probably worth creating a new environment file (env-github_com.enc)

**Comment by andrewstec** [comment]
We need to re-gain access to the `atest-01, atest-02, and atest-03` accounts. We have to see if we can determine what email they were created with.

**Comment by winstan** [comment]
Probably get the passwords from Reid.

**Comment by andrewstec** [comment]
*E-mailed Reid requesting access*

**Comment by winstan** [comment]
Passwords have been reset, and all accounts are functional (after 02+03 being flagged).

**Comment by andrewstec** [comment]
> Passwords have been reset, and all accounts are functional (after 02+03 being flagged).

Awesome! We are unblocked and can continue with creating a new `.env` file for Github.com. When did we want to prioritize this for?

**Comment by winstan** [comment]
Done by Sept 20?

**Comment by andrewstec** [comment]
We can start this by the end of the week then to make sure that there are no surprises. It should be relatively quick.

**Comment by andrewstec** [comment]
Fixed by @rtholmes .
