### ISSUE TITLE
Classlist API update status

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#269]
It would be great if the `Update classlist with API` button gave some kind of status about what changed (aka, how many new students were added, old students were removed, and students were updated). 

This would be helpful because if students were added we would know that we must provision new repos (removed and updated are just nice to know). This might mean giving feedback with a modal instead of a toast, but that is totally fine.

**Comment by andrewstec** [comment]
@rtholmes 

I am part-way in the implementation and I just want to update you with the business logic taking shape and a slight technical approach issue:

Business Logic Further Detail:
- Regarding the removed students, we do not currently remove students from the Classlist in Classy (the `people` table). Therefore, I am segmenting the students who are removed from the API data but exist in the database.
- Regarding the updated students, if a student exists prior to a latter classlist update, the database will technically still update them. As that information is redundant, I am segmenting the students in the `updated` section only if a property has changed.
- Finally, we are having some multi-modal loading issues. If I show a modal, and do not block the thread waiting for feedback from the user (such as with a while loop), then the 

Technical Approach Issue:
"Retrieving Deliverable" modal pops-up afterwards and blocks my modal. Is it okay to move forward with blocking the thread or would you prefer an alternative approach like creating a page to display the logic on?

I do not have a strong personal opinion on this, but I know a lot of people do not like blocking the thread. Please let me know if you have a preference.

**Comment by rtholmes** [comment]
I don't think you want to remove people, but if a student is no longer in the course you can update their kind field (e.g., `person.kind = PersonKind.WITHDRAWN` (this is in the tests somewhere).

I think there must be a better way than blocking the thread. If you need to show a modal that is asking for input shouldn't it just kick off the second task once that input has been given?

**Comment by andrewstec** [comment]
> I don't think you want to remove people, but if a student is no longer in the course you can update their kind field (e.g., `person.kind = PersonKind.WITHDRAWN` (this is in the tests somewhere).

I absolutely agree with the above. We will have to separate the withdrawn logic from this task, but we can put the withdrawn logic in the backlog to complete soon.

> I think there must be a better way than blocking the thread. If you need to show a modal that is asking for input shouldn't it just kick off the second task once that input has been given?

I think we are using different definitions of modals. I can put the change details in confirmation windows that have to be acknowledged, but I do not think we can use a Modal component from Onsen UI because of the problem above: 

ie. Two modals load, as the Modal component will not wait for input.
![image](https://user-images.githubusercontent.com/7872295/65191054-a480e080-da27-11e9-9710-2b03fee6d739.png)

Either way, I will definitely stay away from blocking the thread.

**Comment by andrewstec** [comment]
@rtholmes 

Just a heads-up that the confirmation notification worked perfectly. 

Thanks!

**Comment by andrewstec** [comment]
Reference to pull-request #275: https://github.com/ubccpsc/classy/pull/275

**Comment by andrewstec** [comment]
*Released in https://circleci.com/gh/ubccpsc/classy/1162*
