### ISSUE TITLE
Upstream 310 changes

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#272]
We've made many team formation, logging, and UI improvements in the 310 fork and we'd like to upstream them to master. Some we want to merge, and some we don't. How might we go about this?

Things we want to merge are changes to these files:

```
packages/autotest/src/autotest/AutoTest.ts
packages/autotest/src/autotest/ClassPortal.ts
packages/autotest/src/autotest/Queue.ts
packages/autotest/src/github/GitHubAutoTest.ts
packages/autotest/src/github/GitHubUtil.ts
packages/autotest/test/GitHubUtilSpec.ts
packages/common/Config.ts
packages/common/Log.ts
packages/common/TestHarness.ts
packages/common/types/ContainerTypes.ts
packages/common/types/PortalTypes.ts
packages/portal/backend/src-util/FrontendDatasetGenerator.ts
packages/portal/backend/src/Factory.ts
packages/portal/backend/src/Types.ts
packages/portal/backend/src/controllers/AdminController.ts
packages/portal/backend/src/controllers/AuthController.ts
packages/portal/backend/src/controllers/CourseController.ts
packages/portal/backend/src/controllers/DatabaseController.ts
packages/portal/backend/src/controllers/GitHubController.ts
packages/portal/backend/src/controllers/GradesController.ts
packages/portal/backend/src/controllers/PersonController.ts
packages/portal/backend/src/controllers/RepositoryController.ts
packages/portal/backend/src/controllers/ResultsController.ts
packages/portal/backend/src/controllers/TeamController.ts
packages/portal/backend/src/custom/DefaultCourseController.ts
packages/portal/backend/src/server/common/AdminRoutes.ts
packages/portal/backend/src/server/common/AuthRoutes.ts
packages/portal/backend/src/server/common/AutoTestRoutes.ts
packages/portal/backend/src/server/common/GeneralRoutes.ts
packages/portal/backend/test/FactorySpec.ts
packages/portal/backend/test/controllers/AdminControllerSpec.ts
packages/portal/backend/test/controllers/CourseControllerSpec.ts
packages/portal/backend/test/controllers/GitHubControllerSpec.ts
packages/portal/backend/test/server/GeneralRoutesSpec.ts
packages/portal/frontend/html/admin.html
packages/portal/frontend/html/default/student.html
packages/portal/frontend/html/style.css
packages/portal/frontend/src/app/util/DashboardTable.ts
packages/portal/frontend/src/app/util/SortableTable.ts
packages/portal/frontend/src/app/views/AdminConfigTab.ts
packages/portal/frontend/src/app/views/AdminDashboardTab.ts
packages/portal/frontend/src/app/views/AdminGradesTab.ts
packages/portal/frontend/src/app/views/AdminProvisionPage.ts
packages/portal/frontend/src/app/views/AdminPullRequestsPage.ts
packages/portal/frontend/src/app/views/AdminTeamsTab.ts
```

Things we don't want to merge are changes to these files (approximately):

```
.circleci/config.yml
.env.sample
.nvmrc
deploy-image.sh
docker-compose.310.yml
docker-compose.340.yml
docker-compose.sdmm.yml
docker-compose.yml
docs/310.md
packages/portal/frontend/html/cs310/landing.html
packages/portal/frontend/html/cs310/login.html
packages/portal/frontend/html/cs310/student.html
packages/portal/frontend/src/app/custom/CustomAdminView.ts
packages/portal/frontend/src/app/custom/CustomStudentView.ts
packages/portal/backend/test/cs310/CustomCourseControllerSpec.ts
packages/portal/backend/src/custom/CustomCourseController.ts
packages/portal/backend/src/custom/CustomCourseRoutes.ts
packages/proxy/310.dockerfile
packages/proxy/Dockerfile
packages/proxy/nginx.310.rconf
packages/proxy/nginx.rconf
```

**Comment by rtholmes** [comment]
Just to followup on this; we could merge squash changes into a branch on `ubccpsc/<newBranch>` and then cherrypick out the files into a few big changes. These would be:

* Admin interface improvements (minor usability issues, better rendering in several tables>
* New AutoTest `#schedule` feature
* Important GitHub check on `pushEvent` that was bypassing AutoTest timers
* Improvements to the AutoTest Pull Request tool (for updating student repos once deployed)
* AutoTest queue persistence (reboot the container anytime, queued instances will auto resume)
* Analytic endpoint for monitoring AutoTest duration
* Logging improvements for server-side monitoring (this is just logging changes scattered all over the place)

**Comment by winstan** [comment]
This sounds good to me.

**Comment by rtholmes** [comment]
Just updating this, I won't have time to take care of this upstreaming until next term so we'll just keep working on the 310 fork. If there are features you want from the fork, feel free to pull them up. The current `upccpsc310/master` is up-to-date with `classy/master`.

Pretty much you won't want changes to any of these files, but everything else should be totally good to go:

```
.env.sample
docker-compose.yml
packages/portal/frontend/html/cs310/landing.html
packages/portal/frontend/html/cs310/login.html
packages/portal/frontend/html/cs310/student.html
packages/portal/frontend/src/app/custom/CustomAdminView.ts
packages/portal/frontend/src/app/custom/CustomStudentView.ts
packages/portal/backend/test/cs310/CustomCourseControllerSpec.ts
packages/portal/backend/src/custom/CustomCourseController.ts
packages/portal/backend/src/custom/CustomCourseRoutes.ts
packages/proxy/310.dockerfile
packages/proxy/nginx.rconf
```

**Comment by andrewstec** [comment]
@rtholmes 

Thanks for your efforts. I will take a look through this and see what we can do. I will have to touch bases with @winstan tomorrow before merging this in. 

I was looking at the merge logic earlier this afternoon, and all tests passed on the `https://github.com/ubccpsctech/classy/tree/ubccpsctech/merged-310-ubccpsc-code` repo and branch. I just have to remove the mentioned files above and re-try the tests. 

If we can easily merge this tomorrow, are there any additional manual tests that we need to run in addition to the back-end tests passing?

**Comment by rtholmes** [comment]
Heh, I've probably replicated the same thing here:

https://github.com/ubccpsc/classy/pull/274

The tests should finish cleanly and we'll be good to go. But the way I did it (by removing the files from master) is likely to cause issues when syncing the fork back with master. I wonder if using `.gitattributes` would be a good way to solve this?

**Comment by andrewstec** [comment]
> Heh, I've probably replicated the same thing here:
> 
> #274
> 
> The tests should finish cleanly and we'll be good to go. But the way I did it (by removing the files from master) is likely to cause issues when syncing the fork back with master. I wonder if using `.gitattributes` would be a good way to solve this?

Thanks for the heads-up. I am reading about `.gitattributes` now. It could certainly, at least, be convenient for our encrypted files. It may be able to help us. Would these be permanent or temporary attributes that you would tentatively want to apply?

**Comment by rtholmes** [comment]
It seems that `.gitattributes` can do lots of things, one of which is enforcing merge strategies. So it might be possible to have a change in a fork always resolve with `mine` (aka ignore any file status info from the master). Normally this wouldn't be a great solution, but in this case it really is just a specific list of files (and maybe dirs in the case of `html/cs310`).

**Comment by andrewstec** [comment]
I think this strategy makes sense, but it may get confusing down the road if you ever want to merge files back into the master fork but have found another fork has made changes that they are dependent on in the same files. The 310 specific files should not be an issue, but we may run into issues with CircleCI configuration and custom class files (though probably easy to fix).

I will speak to @winstan about that idea tomorrow. It could be a good solution. I know that @winstan has thought a fair amount about how we can divide core and periphery code. He likely has some good thoughts on this.

**Comment by andrewstec** [comment]
`ubccpsc/classy/master` code merged into downstream `ubccpsctech/classy/master` on https://github.com/ubccpsctech/classy/commit/ac7296cafd38cea79844b363bd6f36faef382762.
