### ISSUE TITLE
Strengthen GitHubAutoTest scheduling tests

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#282]
Will probably involve some simplification of the existing code along the way. This work will mainly be in `checkCommentPreconditions` and `processExecution`.

**Comment by rtholmes** [comment]
@andrewstec tracking these improvements here. I can try this in 310 production starting tomorrow (deadline tonight).

**Comment by andrewstec** [comment]
@rtholmes I am watching and currently just going through the logic to bring myself up to speed with where you are going. I will run upstairs to touch bases with you if you are around.

**Comment by rtholmes** [comment]
@andrewstec the tests are back passing again (I was testing against github.com locally, not github.ubc). You could upstream the queue handling updates anytime that works for you (and we can think about ways to better test this whole process that does not require quite as much boilerplate code).

**Comment by andrewstec** [comment]
Code merged in https://github.com/ubccpsc/classy/commit/bb9f9fbd51d15380c32114471d532fd926a8955e. 

Tests pass, schedule feature works when manually tested on https://classy-dev.cs.ubc.ca.
