### ISSUE TITLE
Admin does not get AutoTest feedback when item closed and queued

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#283]
Bug: An _admin_ cannot request grade feedback for an assignment when an assignment is queued for processing _and_ the assignment is closed. The admin is given feedback that says, "This commit has been queued for processing against [labX]. Your results will be posted here as soon as they are ready." but then no feedback is given.

Note: After the assignment stops processing, the admin can successfully request grade feedback. Since there is a workaround, this issue is a medium priority for development.

Story: As an admin, I want to be able to request feedback for a closed assignment while it is queued for processing or after its processing is finished so that I can see the grade results.

**Comment by rtholmes** [comment]
Confirmed fixed on the 310 branch: https://github.students.cs.ubc.ca/CPSC310-2019W-T1/project_team256/commit/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819

Some key log statements (many removed, but this corresponds to the request on the closed deliverable in the issue above):

```
autotest                | <I> 2019-10-8 17:27:11: RouteHandler::postGithubHook(..) - start; handling event: commit_comment; signature: sha1=e5b1f2fcb21a1a6fd6fd329af870269be99cec18
autotest                | <I> 2019-10-8 17:27:11: GitHubAutoTest::checkCommentPreconditions(..) - admin request; ignoring openTimestamp and closeTimestamp
autotest                | <I> 2019-10-8 17:27:11: GitHubAutoTest::checkCommentPreconditions(..) - valid comment; preconditions accepted
autotest                | <I> 2019-10-8 17:27:11: AutoTest::addToStandardQueue(..) - start; commit: f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
autotest                | <I> 2019-10-8 17:27:11: AutoTest::tick(..) - start; standard - #wait: 1, #run: 0; express - #wait: 0, #run: 0; regression - #wait: 0, #run: 0;schedule - #wait: 0.
autotest                | <I> 2019-10-8 17:27:11: Queue::scheduleNext() - standard done; delivId: d1; commitURL: https://github.students.cs.ubc.ca/CPSC310-2019W-T1/project_team256/commit/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
autotest                | <I> 2019-10-8 17:27:11: AutoTest::tick(..) - starting job on: standard; deliv: d1; repo: project_team256; SHA: f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
autotest                | <I> 2019-10-8 17:27:11: AutoTest::handleTick(..) - start; delivId: d1; SHA: f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
autotest                | <I> 2019-10-8 17:27:11: AutoTest::tick(..) - done: standard - #wait: 0, #run: 1; express - #wait: 0, #run: 0; regression - #wait: 0, #run: 0.
autotest                | <I> 2019-10-8 17:27:11: GitHubAutoTest::schedule(..) - scheduling completed for: https://github.students.cs.ubc.ca/CPSC310-2019W-T1/project_team256/commit/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
autotest                | <I> 2019-10-8 17:27:11: MongoDataStore::saveComment(..) - start; delivId: d1; repo: project_team256; url: https://github.students.cs.ubc.ca/CPSC310-2019W-T1/project_team256/commit/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
autotest                | <I> 2019-10-8 17:27:11: GitHubAutoTest::postToGitHub(..) - posting message to: https://github.students.cs.ubc.ca/api/v3/repos/CPSC310-2019W-T1/project_team256/commits/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819/comments
autotest                | <I> 2019-10-8 17:27:11: GitHubUtil::postMarkdownToGithub(..) - Posting markdown to url: https://github.students.cs.ubc.ca/api/v3/repos/CPSC310-2019W-T1/project_team256/commits/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819/comments; message: This commit has been queued for processing against d1. Your results will be post...
autotest                | <I> 2019-10-8 17:29:04: AutoTest::handleExecutionComplete(..) - start: delivId: d1; repoId: project_team256; took (waiting + execution): 1 minute and 52 seconds; SHA: f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
portal                  | <I> 2019-10-8 17:29:04: AutoTestRouteHandler::atPostResult(..) - start
portal                  | <I> 2019-10-8 17:29:04: ResultsController::validateGradeReport(..) - done; report is valid
portal                  | <I> 2019-10-8 17:29:04: ResultsController::validateAutoTestResult(..) - done; object is valid
portal                  | <I> 2019-10-8 17:29:04: AutoTestRouteHandler::performPostResult(..) - valid result && valid secret; deliv: d1; repo: project_team256; sha: f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
portal                  | <I> 2019-10-8 17:29:04: DeliverablesController::getDeliverable( d1 ) - start
portal                  | <I> 2019-10-8 17:29:04: ResultsController::createResult(..) - start
autotest                | <I> 2019-10-8 17:29:04: GitHubAutoTest::postToGitHub(..) - posting message to: https://github.students.cs.ubc.ca/api/v3/repos/CPSC310-2019W-T1/project_team256/commits/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819/comments
autotest                | <I> 2019-10-8 17:29:04: GitHubUtil::postMarkdownToGithub(..) - Posting markdown to url: https://github.students.cs.ubc.ca/api/v3/repos/CPSC310-2019W-T1/project_team256/commits/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819/comments; message: **Public test results**
```

**Comment by andrewstec** [comment]
> Confirmed fixed on the 310 branch: https://github.students.cs.ubc.ca/CPSC310-2019W-T1/project_team256/commit/f1bdb7c15ecef5f46e938ab674e2c9e6cecc7819
> 

I do not have access to the link above, but I am glad that it was fixed. We would gladly cherry-pick those changes and move them into the `ubccpsc` project.

**Comment by andrewstec** [comment]
@rtholmes Is this something that you can package-up and isolate in a separate branch for us to review?

**Comment by rtholmes** [comment]
I don't think so. I think it's just the same as any other set of merges, I'd just take everything that isn't the course-specific controller files, our course-specific `nginx.conf`, and our course-specific `docker-compose.yml` (all other changes are really just CI and test improvements). You're welcome to sync up the branches however you see fit. We would love to have all your master fixes integrated into the fork too.

**Comment by andrewstec** [comment]
We will do our best to get this sorted soon, Reid. This is a beyond the scope that we were looking at for at the moment with the fix. The fix was also in the backlog and not scheduled for the moment. We will have to hold up on this for now. 

The reason that I do not want to merge this too quickly is that we need to watch the code quality (or else we may lose some changes in the 310 or ubccpsc branch or introduce a bug).

**Comment by rtholmes** [comment]
No rush on our end, you can merge however fits your own cadence!

**Comment by andrewstec** [comment]
Code merged in https://github.com/ubccpsc/classy/commit/bb9f9fbd51d15380c32114471d532fd926a8955e. 

Issue works when manually tested on https://classy-dev.cs.ubc.ca.
