### ISSUE TITLE
Feature Documentation

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#284]
@rtholmes 

You mentioned some relevant 310 documentation that explain what some of the Classy/AutoTest features are, such as #scheduling. 

Could you please merge that into a branch for us to look at? We would like to include it in the overall documentation.

**Comment by rtholmes** [comment]
It is already in master: https://github.com/ubccpsc/classy/blob/master/docs/autotest.md

**Comment by rtholmes** [comment]
I sent you a message and a link about this on slack yesterday too I think.

**Comment by andrewstec** [comment]
> I sent you a message and a link about this on slack yesterday too I think.

Thanks! 

(No Slack message, but I will try to access the account that I think it was sent to)
