### ISSUE TITLE
Classy student delay cannot be set under 900 seconds

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#288]
Issue: The student delay cannot be set lower than 900 seconds from the UI. 

Actual: After setting the time in the range of 0 to 899 seconds and saving the deliverable settings in Portal, the student delay time defaults back to 900 seconds.

Expected: After setting the time in the range of 0 to 899 seconds and saving the deliverable settings in Portal, the student delay time is set in the range of 0 to 899 seconds.

AutoBot is responding with the incorrect timing delay: 

![image](https://user-images.githubusercontent.com/7872295/67402717-c52be100-f565-11e9-9c33-f18e825330de.png)

Steps to recreate: 

1. Open a deliverable in Portal's Admin Configuration.
2. Set the time as anywhere between 0-899 seconds.
3. Click the 'save' button.
4. Re-open the deliverable and see that the time is set as 900 seconds.

**Comment by andrewstec** [comment]
Update:

This is not actually a bug, but the UI instructions offered more options than were available due to this restriction. The restriction of a 15 minute minimum delay has been modified. It can now be substituted with a time preference to default to if it is parameterized in the `.env` file. 

Work done in this PR: https://github.com/ubccpsc/classy/pull/295.

**Comment by andrewstec** [comment]
*Merged*

**Comment by rtholmes** [comment]
@andrewstec I might recommend some docs cautioning setting too low of limits. We already get multi-hour pile ups during busy times for 310 with a 12 hour timeout. While 15 minutes makes sense for labs, it could expose the server to untenable load if, for instance, all 600 210 students had a 5 minute timeout and a common deadline.

**Comment by andrewstec** [comment]
@rtholmes 

I fully understand and I think that is a good idea. We can explain how to avoid pile-ups in general and mention the greater likelihood of the pile-up with a smaller minimum delay. I will turn that into an issue that I will work on.

Out of curiosity, is there any future plan to increase the number of running queue items? I realize that scaling up is a limitation, but are there future horizontal scaling plans to process queue items?

**Comment by rtholmes** [comment]
@andrewstec this is a good question and is probably worth opening an issue on so we can have a longer discussion. There are two approaches:

1. The easy one. Provision the VMs larger, and tell `Queue` to run more concurrent runs. This will work and can be done in 15 minutes.

2. The hard one. Have a dedicated AutoTest VM that is shared across all courses with the understanding that most of the time courses are not facing deadlines so the average utilization will be low, but when it is high many more concurrent instances can be handled (e.g., as a first stab I would aim to handle ~50 concurrent instances across all courses). This would require some backend work, but we thought about this in advance so it would be _compatible_ (although not exactly easy) with our current architecture.
