### ISSUE TITLE
Queue Upgrade: Limitations and Solutions

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#300]
# Issue

The queue is currently a JSON file on the Classy VM that stores a backlog of information to be graded. A Docker container is run for each item in the queue that must be graded, which currently occurs on the Classy VM. As the VM has a memory and CPU limit, there is a maximum number of assignments that can be marked simultaneously, which results in a pile-up of assignments to be graded during peak times. The effect of the pile-up on the students is a long wait before they can receive grade feedback from AutoBot during critical moments.

To resolve the pile-up, we can scale horizontally or vertically. 

## Vertically 

- increase the CPU and memory of the VM
- change the configured number of containers that can simultaneously be processed by AutoTest's queue system

## Horizontally

- create a resource that meets the CPU and memory requirements to grade student assignments
- set a maximum number of items that can be graded at once based on the resource limitations
- create and integrate a new queue that Classy can store the backlog of grading assignments in
- create a poller that triggers the grading of an assignment based on our maximum defined number of items
- take output container grade and persistent information and integrate it with Classy/AutoBot

**Comment by andrewstec** [comment]
@rtholmes Just to follow-up, we can discuss the queue situation here if you would like, and brainstorm potential approaches. It sounds like this is an epic that would require a fair amount of discussion and planning.

**Comment by andrewstec** [comment]
Just an idea: If you want to scale vertically without an limitations, we may consider an AWS integration that uses Lambda functions: 

"AWS Lambda lets you run code without provisioning or managing servers. You pay only for the compute time you consume - there is no charge when your code is not running.

With Lambda, you can run code for virtually any type of application or backend service - all with zero administration. Just upload your code and Lambda takes care of everything required to run and scale your code with high availability. You can set up your code to automatically trigger from other AWS services or call it directly from any web or mobile app."

- https://aws.amazon.com/lambda/

It may be tricky to capture logging with serverless functions though. I think it is much easier to capture the logging on a permanent host that runs the Docker container for a grade. Amazon would want you to capture logging in their services, which requires more integration work and money, which is something that I would like to avoid. The only reason why I am considering this as a potential option is that there would never be a pile-up of student code to be marked. It looks like the cost would be minimal too. The cost would be tricky to calculate without any experimentation. Amazon provides dead letter queues that could capture failed Lambda functions.

Unfortunately, this is not a simple development task either. Price wise though, this looks very viable for a cheap solution that allows you to scale enormously and eliminate queue pile-ups.

**Comment by rtholmes** [comment]
Absolutely Lamdas would be a great way to go. One way we could think about this is using Maelstorm (https://maelstromapp.com) as an intermediary so we could spin these jobs up locally or w/ Amazon via SQS. I think the other interesting question here is really around the machine that hosts our VMs now: what kind of capacity does it have, and how many concurrent jobs could it handle if we made it so the course instances were sized just for Classy and the AutoTest containers for all courses were all hosted in some common space?

**Comment by andrewstec** [comment]
Maelstorm looks ideal. I can't say that I have heard of it until now though.

I will find out about our maximum vertical capacity. Scaling vertically is likely the easiest thing to do in the meantime.

Do you collect any stats on your Docker container execution times and resource usage? It might be a good idea to record some metrics just to get a ballpark estimate.

**Comment by rtholmes** [comment]
Michael Sanderson probably has a good idea of where we're at. Our containers run in 5 mins in the worst case (60 seconds typically). They only need 512 MB memory typically, but having access to 2GB would be better. They could probably make do with one CPU, but two is better and more than two is not required.

**Comment by rtholmes** [comment]
Marking as #wontfix. Queues have been updated in #410 to make them more heavily favour the express queues. Courses should manage their loads by setting a reasonable minimum interval between requests, or asking the staff for more cores to increase the standard (or express) queue count.
