### ISSUE TITLE
CS310 Upstream: Coordinating Merge

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#304]
I wanted to see if we could start to identify the files that you want to eliminate in the upstream merge to `ubccpsc/Classy`.

I brought in the latest code on both `ubccpsc310` and `ubccpsc`. When using the `--squash` flag to merge the `ubccpsc310` master code into the `ubccpsc` master code, there were only 17 modifications: 

```
	modified:   docker-compose.yml
	modified:   packages/autotest/src/autotest/AutoTest.ts
	modified:   packages/autotest/src/autotest/ClassPortal.ts
	modified:   packages/autotest/src/github/GitHubAutoTest.ts
	modified:   packages/autotest/src/github/GitHubUtil.ts
	modified:   packages/autotest/test/GitHubEventSpec.ts
	modified:   packages/common/types/ContainerTypes.ts
	modified:   packages/portal/backend/src-util/TransformGrades.ts
	modified:   packages/portal/backend/src/controllers/AdminController.ts
	modified:   packages/portal/backend/src/controllers/CourseController.ts
	modified:   packages/portal/backend/src/controllers/DatabaseController.ts
	modified:   packages/portal/backend/src/controllers/GradesController.ts
	modified:   packages/portal/backend/src/controllers/ResultsController.ts
	modified:   packages/portal/backend/src/server/common/AutoTestRoutes.ts
	modified:   packages/portal/backend/src/server/common/CSVParser.ts
	modified:   packages/portal/backend/test/controllers/DatabaseControllerSpec.ts
	modified:   packages/portal/frontend/html/admin.html
```

I am just about to merge this in a testing branch on `ubccpsctech` and run the tests to see what happens. The files above appear appropriate to merge into `ubccpsc/master`. The only file that worried me was `docker-compose.yml`, but it has a very minor MongoDB change to change log output.

**Comment by andrewstec** [comment]
Both the CI tests and Docker container build works with the squashed code on the `ubccpsctech` branch. 

![image](https://user-images.githubusercontent.com/7872295/68969446-d7322580-0799-11ea-8356-23b14ee311c3.png)

Since there are no conflicts, and no files that I am particularly concerned about merging, I think we can proceed with setting up a pull-request to the `ubccpsc/master` branch from `ubccpsc310/master` with the outlined new features and modifications. @rtholmes Do you have any concern about merging the files outlined in the core issue into `ubccpsc/master`?

**Comment by rtholmes** [comment]
Let's just hold off on the PR yet... we're doing some performance analysis on problems we only see in 310 when it's under load that we'd like to try to get a handle on before we sync up.

**Comment by andrewstec** [comment]
> Let's just hold off on the PR yet... we're doing some performance analysis on problems we only see in 310 when it's under load that we'd like to try to get a handle on before we sync up.

Sounds good!

**Comment by andrewstec** [comment]
@rtholmes Do you have an ETA regarding the performance analysis problem? Please let me know. I will plan around that.

**Comment by rtholmes** [comment]
@andrewstec they are done and pushed. The only things that will change on the 310 fork now are the 310-specific updates for the end-of-term.

**Comment by andrewstec** [comment]
Okay, that's great news @rtholmes. It sounds like we can continue with the upstream then. Want me to run throw the above logic one more time?

**Comment by rtholmes** [comment]
Sure, give it a whirl. I expect there to be more changes now because the performance and logging work required a more expansive set of edits (but all tests are passing and it has run successfully in production).

**Comment by andrewstec** [comment]
The scope of the changes are not too bad: 

```
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   docker-compose.yml
	modified:   packages/autotest/src/autotest/AutoTest.ts
	modified:   packages/autotest/src/github/GitHubAutoTest.ts
	modified:   packages/autotest/src/github/GitHubUtil.ts
	modified:   packages/autotest/src/server/RouteHandler.ts
	modified:   packages/autotest/test/GitHubAutoTestSpec.ts
	modified:   packages/autotest/test/GitHubEventSpec.ts
	modified:   packages/common/types/ContainerTypes.ts
	modified:   packages/portal/backend/src-util/DatabaseValidator.ts
	modified:   packages/portal/backend/src-util/TransformGrades.ts
	modified:   packages/portal/backend/src/Factory.ts
	modified:   packages/portal/backend/src/controllers/AdminController.ts
	modified:   packages/portal/backend/src/controllers/CourseController.ts
	modified:   packages/portal/backend/src/controllers/DatabaseController.ts
	modified:   packages/portal/backend/src/controllers/GitHubActions.ts
	modified:   packages/portal/backend/src/controllers/GradesController.ts
	modified:   packages/portal/backend/src/controllers/PersonController.ts
	modified:   packages/portal/backend/src/controllers/RepositoryController.ts
	modified:   packages/portal/backend/src/controllers/ResultsController.ts
	modified:   packages/portal/backend/src/controllers/TeamController.ts
	modified:   packages/portal/backend/src/server/common/AutoTestRoutes.ts
	modified:   packages/portal/backend/src/server/common/CSVParser.ts
	modified:   packages/portal/backend/test/controllers/DatabaseControllerSpec.ts
	modified:   packages/portal/frontend/html/admin.html
	modified:   packages/portal/frontend/src/app/views/AdminDashboardTab.ts
	modified:   packages/portal/frontend/src/app/views/AdminResultsTab.ts

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   packages/autotest/src/autotest/ClassPortal.ts
```

There is a conflict on ClassPortal.ts. I am just going to resolve it. If we can avoid conflicts in the future, we should, but we got lucky this time because it is very simple conflict!

**Comment by andrewstec** [comment]
@rtholmes I am satisfied that these changes are in scope of `ubccpsc` from looking at the files involved. 

The tests also pass. 

![image](https://user-images.githubusercontent.com/7872295/69377662-9b97cf80-0c61-11ea-8167-3e9edf6623d1.png)

Do you have any concerns about the files involved in this merge? I am happy to merge this code.

**Comment by rtholmes** [comment]
Glad it worked out. Feel free to sync the branches up then, looks good to me! I'll still be updating 310 as we deal with the final changes for the term, but it won't be anything major.

**Comment by andrewstec** [comment]
Merged in commit: 76d5ddb0622bdbd49d8412bb921e1f6bcd716777.

**Comment by andrewstec** [comment]
> Glad it worked out. Feel free to sync the branches up then, looks good to me! I'll still be updating 310 as we deal with the final changes for the term, but it won't be anything major.

Did you want me to wait a little while before merging the code downstream to your branch? I can certainly merge the code into your branch sooner rather than later. Just let me know what you prefer. I suppose it shouldn't make much of a difference if I merge it now though, eh?

**Comment by rtholmes** [comment]
You can do it now while it's a big change and maybe we'll do it once more in a couple of weeks for the last bits? Tamara and William have both asked me for a new feature I need to add and it's probably easier in the branch (so I can try it on the server) than on master.
