### ISSUE TITLE
CPSC 340 Gardening

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#32]
@jopika, @mgelbart , there are a few cleanups needed for the 340 code; the tests should pass:

https://circleci.com/gh/ubccpsc/classy/51 (this is the repo visibility test failing)

And some more coverage work is needed, e.g.,:

https://coveralls.io/builds/18036379/source?filename=src/controllers/340/AssignmentController.ts
https://coveralls.io/builds/18036379/source?filename=src/server/340/CS340REST.ts

**Comment by rtholmes** [comment]
Once the test is passing hopefully this will clear up too:

https://coveralls.io/builds/18036379/source?filename=src/controllers/util/GitHubActions.ts#L711

**Comment by jopika** [comment]
The test is fixed, was an ordering issue (the repositories/teams were being wiped before my test could run). 

I'll be adding more code coverage after I finish my repository creation code.

**Comment by jopika** [comment]
Tests have been added; will continue adding tests as needed.
