### ISSUE TITLE
Request library deprecated

### ISSUE THREAD

**Issue by andrewstec** [ubccpsc/classy#335]
`Request` has been deprecated, which affects a library that we heavily use: `request-promise-native`. We may want to discuss the replacement.

Read about the deprecation here: https://github.com/request/request/issues/3142.

Here is a very useful replacement comparison guide: https://github.com/sindresorhus/got#comparison.

Does anyone have a preferable replacement? Do we want more functionality in a request library? Do we want to keep things simple and consistent on the front-end by using `fetch`?

If anyone sees any issues with a potential replacement, please let me know. I will start delving into this as well.

**Comment by andrewstec** [comment]
@rtholmes 

Are you for or against replacing `request`? It seems like we will inevitably have to do this. Any thoughts on this issue?

**Comment by rtholmes** [comment]
@andrewstec go for it. Just make sure you choose a library that works in the browser as well as node. I think we already depend on `superagent` for testing, and that seems to be one of the options. `bent` also looks simple and small.

**Comment by andrewstec** [comment]
@rtholmes `Superagent` is the likely winner based on what I have seen so far. `Bent` looks like a lot of fun and it is sufficient, but it may be a tiny bit premature because of some of the issues that I see are filed (ie. returning a promise instead of an error object).

I will start implementing it and see what sort of obstacles come up. Thanks!

**Comment by andrewstec** [comment]
Just a minor note that there are some `rejectUnauthorized` option limitations in Superagent, so I am taking a quick look at other libraries where we do not have to set the reject unauthorized option in the process.

**Comment by andrewstec** [comment]
It turns out using our own user agent was not an option with `Supertest`, so I used `fetch` instead, which includes it as an option. In addition, keeping the same `option` convention is resulting in very similar looking code. `Supertest`'s chaining would have required more changes.

**Comment by rtholmes** [comment]
Great. `fetch` is probably the right choice anyways since it doesn't have any dependencies at all!

**Comment by andrewstec** [comment]
@rtholmes I should mention that this is `node-fetch`. 

It has minimal dependencies: 

```	
"dependencies": {
		"data-uri-to-buffer": "^3.0.0",
		"fetch-blob": "^1.0.5"
```

**Comment by andrewstec** [comment]
I am going to jump to the front-end and take a look at the Docker build view, which is the only part that I am worried about integrating with `fetch`. I will have more info soon.

**Comment by andrewstec** [comment]
We are totally good from what I have seen so far. The implementation is working and Nick used XHR on the front-end for the Docker build, so that logic is already managed.

**Comment by andrewstec** [comment]
PR here: https://github.com/ubccpsc/classy/pull/337.

**Comment by andrewstec** [comment]
Request has been replaced with `node-fetch` and merged.

Many yarn installation warnings have disappeared, and the remainders can likely be eliminated by upgrading dependencies: 

Back-end:
```
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > watchpack > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+. Upgrade to fsevents 2 with massive improvements.
warning webpack > watchpack > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack > watchpack > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning workspace-aggregator-3838e4b6-4faf-4861-a7c4-31756da10353 > autotest > mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning workspace-aggregator-3838e4b6-4faf-4861-a7c4-31756da10353 > autotest > coveralls > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

AutoTest: 
```
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > watchpack > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+. Upgrade to fsevents 2 with massive improvements.
warning webpack > watchpack > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack > watchpack > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning workspace-aggregator-c3a11942-e7a2-4d91-898e-74eff60125f4 > portal-backend > mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning workspace-aggregator-c3a11942-e7a2-4d91-898e-74eff60125f4 > portal-backend > coveralls > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning workspace-aggregator-c3a11942-e7a2-4d91-898e-74eff60125f4 > portal-frontend > onsenui > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning workspace-aggregator-c3a11942-e7a2-4d91-898e-74eff60125f4 > portal-frontend > onsenui > gulp-protractor > protractor > webdriver-manager > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[3/5] Fetching packages...
```

I will continue to work through these warnings once CPSC310 code is merged, as syncing forks is a priority before the next term.

**Comment by andrewstec** [comment]
As part of the CPSC310 code merge, it was necessary to remove the `request` library in the CPSC310 fork.

This issue will be resolved once this PR is merged: https://github.com/ubccpsc310/classy/pull/57.
