### ISSUE TITLE
Separate creating repos from provisioning them.

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#37]
This will be implemented in `GitHubController::createRepository(..)` and `GitHubController::releaseRepository(..)`.

Since the `Deliverable` object is heavily used (and queried) we should be mindful about adding too much metadata there; wherever possible metadata should be added to `Repository` and `Team`.

**Comment by jopika** [comment]
Merged functionality in cbcc3d569a8cf58598113ed71597c74e61341e62.

**Comment by rtholmes** [comment]
Reopening until `GitHubControllerSpec` is updated with tests for this; `GitHubController` && `GitHubAction` had 80/90% coverage before this change (40/85% now).

**Comment by jopika** [comment]
Tests have been added; as of e9e0a28ee0a5b0c7bbd67e726e2de80a1dec3b1c, passing and coverage has increased to 80+/85+ % again.
