### ISSUE TITLE
Interleave (or freeze) headers on the grades view

### ISSUE THREAD

**Issue by elisabaniassad** [ubccpsc/classy#370]
It would be great if headers could be interleaved in the grades view.  Or if the headings are frozen.

_As an instructor, I would like to be able to see the header for each student's grade row right above their grade row so that I don't have to count columns to figure out which grade is which (and potentially counting wrong) when finding out a student's grade._

**Comment by winstan** [comment]
This seems like something reasonable to add to classy core. Hopefully Onsen UI gives us a way to do this...
