### ISSUE TITLE
Cooldowns are not enforced well when the queue is overloaded

### ISSUE THREAD

**Issue by Bryce-MW** [ubccpsc/classy#392]
It seems to be that the cooldown for requesting is after receiving feedback. So like if I push two commits and ask autobot for a grade on both of them before receiving a grade on either, then it will let me submit both and I will get a grade for both. See these commits for example (if you have access to the 310 student repos):

https://github.students.cs.ubc.ca/CPSC310-2021W-T1/c0_team376/commit/70b8185036a3c1de2c46ec2783ef64011f95ab98#comments

https://github.students.cs.ubc.ca/CPSC310-2021W-T1/c0_team376/commit/13e45b242a72276a174f88aaa0f4f585d1c166bb#comments

I asked for a grade on the first one at 6:30 and received a grade at 8:24. The second one I asked at 7:00 and received a grade at 8:23. There’s no way that should be allowed by the cooldown (3 hours at this time). I kinda found it by accident, I wasn’t trying to find a way around the cooldown.

It seems like the cooldown starts once you receive feedback but is only enforced on asking for new feedback, it won’t impact existing requests.

I think that fixing #390 would also fix this since then asking for another grade before you got the first one back would just replace the first one and you would only get one grade. If you wanted both, you would have to wait until you get a response to one of them then wait the cooldown then ask for the other. Another possibility is to make the cooldown start when you commented asking for a grade which may be more fair on a long queue. Then you also have to decide if replacing your queued commit with a new one would also change the time that the cooldown starts.

**Comment by rtholmes** [comment]
fixed by PR #410
