### ISSUE TITLE
If you delete a repository and then re-provision it, it is already set as released

### ISSUE THREAD

**Issue by braxtonhall** [ubccpsc/classy#416]
OK latest annoyance: If you delete a repository and then re-provision it, it is still set as released, when it really should be unreleased

_Originally posted by @braxtonhall in https://github.com/ubccpsc/classy/issues/410#issuecomment-1258464533_

**Comment by braxtonhall** [comment]
OK so the real problem is that data is duplicated in `Repository` and in `Team`. `Team.custom.githubReleased` is appropriately `undefined`, but `Repository.custom.githubAttached` needs to get set to `false` -- I _think_

**Comment by rtholmes** [comment]
@braxtonhall do you know if this is still an open issue now that #418 and #410 have been merged and deployed to prod for 310?

**Comment by braxtonhall** [comment]
Yes this has been fixed sorry
