### ISSUE TITLE
Config booleans are always true

### ISSUE THREAD

**Issue by braxtonhall** [ubccpsc/classy#420]
In javascript
```javascript
> Boolean("false")
true
```

I think this was not known when the following lines in the Config were written

https://github.com/ubccpsc/classy/blob/90aa2abb9d5871012952b9ec083d59f2c51f9e53/packages/common/Config.ts#L116

and

https://github.com/ubccpsc/classy/blob/90aa2abb9d5871012952b9ec083d59f2c51f9e53/packages/common/Config.ts#L163

**Comment by rtholmes** [comment]
This is probably causing #426. Hopefully:  #[6287613](https://github.com/ubccpsc/classy/pull/424/commits/6287613d5a568487b38cf6ba794e9561b42ec454) fixes the problem.
