### ISSUE TITLE
Update to modern versions of key dependencies

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#428]
* Node - existing: v12; current: v18 is LTS until 2025-05.
* Typescript - existing: 3.7.2; current: v4.8.4.
* Mongo - existing: 3.0.2; current: v5 is LTS until 2025, but probably want to check v6 first.

Docker is currently v18, this is probably ok and not worth changing.

**Comment by winstan** [comment]
Classy dependencies are almost entirely contained within docker. Here's an exhaustive list of packages installed on the host itself for Classy:

- git
- docker-ce
- python3-docker
- certbot

We also install docker-compose.

**Comment by rtholmes** [comment]
Some aspect of this ended up breaking container provisioning. This code is complex to debug as it uses http-streams to send updates from docker as it builds to the container to AutoTest to Portal and on to the browser. We should probably re-open this PR so these changes are not lost while we try to figure out which aspect of this is causing the problem.

**Comment by winstan** [comment]
Changes to track are in the [modernize_dependencies_v1](/ubccpsc/classy/tree/modernize_dependencies_v1) branch

**Comment by rtholmes** [comment]
This was all finished and deployed.
