### ISSUE TITLE
Validate container output

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#50]
The Grader service should validate the report from the container that all the fields are present and that there is a non-empty message.

**Comment by rtholmes** [comment]
Portal will call the grader on this, even if grader doesn't check it itself once it tries to upload the record:

https://github.com/ubccpsc/classy/blob/master/packages/portal/backend/src/controllers/ResultsController.ts#L181

**Comment by rtholmes** [comment]
@nickbradley just following up on this; when `ClassPortalService` posts to `/portal/at/grade/` with an invalid grade the error will be sent back, to AutoTest here: https://github.com/ubccpsc/classy/blob/master/packages/autotest/src/autotest/ClassPortal.ts#L223 as a 400.

**Comment by nickbradley** [comment]
@rtholmes Just to confirm then, there is no need for the Grader service to validate the `report.json` file generated by the container (otherwise, it'll just pass through whatever is in the file if it exists)?

**Comment by rtholmes** [comment]
I don't think so. If you want to know if there was a problem you can watch
for the 400 and at least log it prominently for container debugging, but
otherwise don't worry about it.
