### ISSUE TITLE
Hardcoded container config

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#56]
The container config values should be coming from the database.

https://github.com/ubccpsc/classy/blob/c68438c2c2c9e2beeba87ba1f8472def2b78c134/packages/portal/backend/src/server/common/AutoTestRoutes.ts#L68-L76

**Comment by rtholmes** [comment]
Will get to this when I'm back. I have set the deliverable values to these already so I just need to hook up the endpoint.
