### ISSUE TITLE
Post error message

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#60]
We probably want autotest to postback something even if the message field is missing. Otherwise, it seems to the user that their commit is queued indefinitely.

Example:
https://github.com/SECapstone/secap_TQgit/commit/887a0a1ab9cf0f2deef74b8e8dfe7b46644c441e#commitcomment-30006065

Code:
https://github.com/ubccpsc/classy/blob/473ce7eaa161761b2a4c7c2207d7743f6c5d1429/packages/autotest/src/github/GitHubService.ts#L43-L46

**Comment by nickbradley** [comment]
This has actually already been reported in #3. I have seen this behaviour in the new SDMM deploy.

**Comment by rtholmes** [comment]
This code has all changed; let us hope this is resolved.
