### ISSUE TITLE
Results for commit

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#61]
I think this should also take a commit sha:

https://github.com/ubccpsc/classy/blob/9a7e997966d8c2b5feede7e7acaf12100bd1e78e/packages/autotest/src/autotest/ClassPortal.ts#L78-L85

**Rationale**
For SDMM, results are not generated for push events. A result record will only be generated the first time a student requests a grade for a particular deliverable because once a result record exists,

https://github.com/ubccpsc/classy/blob/9a7e997966d8c2b5feede7e7acaf12100bd1e78e/packages/autotest/src/github/GitHubAutoTest.ts#L142

that will get a non-null result and so the following will always return the feedback from the first execution:

https://github.com/ubccpsc/classy/blob/9a7e997966d8c2b5feede7e7acaf12100bd1e78e/packages/autotest/src/github/GitHubAutoTest.ts#L170-L180

No grades are computed after the initial run.

**Observation**
Student requested grade on commit 887a0a and got feedback (well container failed so there was no feedback given but that's a separate bug). Student made new commit 8f87c5 and made another request; bot returned result from previous commit:

```
<T> 2018-8-9 13:34:40: RouteHandler::handleWebhook() - comment request: {
  "delivId": "d1",
  "repoId": "secap_TQgit",
  "botMentioned": true,

  ==>"commitSHA": "8f87c5de9df8fbacb68afadf8f96768e8bccd1f8",

  "commitURL": "https://github.com/SECapstone/secap_TQgit/commit/8f87c5de9df8fbacb68afadf8f96768e8bccd1f8",
  "postbackURL": "https://api.github.com/repos/SECapstone/secap_TQgit/commits/8f87c5de9df8fbacb68afadf8f96768e8bccd1f8/comments",
  "personId": "TQgit",
  "timestamp": 1533821679000
}
...
<T> 2018-8-9 13:34:40: ClassPortal::getResult() - sent; returned payload: {"success":[{"delivId":"d1","repoId":"secap_TQgit","commitURL":"https://github.com/SECapstone/secap_TQgit/commit/887a0a1ab9cf0f2deef74b8e8dfe7b46644c441e","commitSHA":"887a0a1ab9cf0f2deef74b8e8dfe7b46644c441e","input":{"delivId":"d1","pushInfo":{"delivId":null,"repoId":"secap_TQgit","cloneURL":"https://github.com/SECapstone/secap_TQgit.git",

==>"commitSHA":"887a0a1ab9cf0f2deef74b8e8dfe7b46644c441e",

"commitURL":"https://github.com/SECapstone/secap_TQgit/commit/887a0a1ab9cf0f2deef74b8e8dfe7b46644c441e","postbackURL":"https://api.github.com/repos/SECapstone/secap_TQgit/commits/887a0a1ab9cf0f2deef74b8e8dfe7b46644c441e/comments","timestamp":1533742341000},"containerConfig":{"dockerImage":"secapstone-grader","studentDelay":43200,"maxExecTime":300,"regressionDelivIds":[],"custom":{}}},"output":{"timestamp":1533742582815,"report":{"custom":[],"errorNames":[],"failNames":[],"feedback":"","passNames":[],"scoreCover":0,"scoreOverall":0,"scoreTest":0,"skipNames":[]},"postbackOnComplete":false,"custom":{},"attachments":[],"state":"SUCCESS"},"people":["TQgit"]}]}
```

**Comment by nickbradley** [comment]
I will hotfix by changing

```js
if (res !== null) { ... }
```
to

```js
if (res !== null && res.commitSHA === info.commitSHA) { ... }
```

**Comment by rtholmes** [comment]
Just another note for reference since it will be near this code as well; the 12h limit is not being enforced (here are 4 runs in less than an hour):
https://github.com/SECapstone/secap_ccunnin8/commit/868af7011eec097476076e393d37c0bb2cf81739
https://github.com/SECapstone/secap_ccunnin8/commit/87c49e6ca0b47441b7e4a0d35a8803c8d2a54a7c
https://github.com/SECapstone/secap_ccunnin8/commit/bdaea9522fbb1c7a7554310ee73e7825c02953ae
https://github.com/SECapstone/secap_ccunnin8/commit/db1ba03a950a1d347cb5c91d3641ebc04a2b381d

**Comment by rtholmes** [comment]
This code has been changed so much I'm just going to close this; we can open new issues if we see these kinds of problems with the new implementation.
