### ISSUE TITLE
Get grade reports

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#64]
Add endpoint to the grading service for getting the stored stdio.txt file for a particular commit and deliverable. For now, proxy requests through a "secret" endpoint specified in the .env.

**Comment by nickbradley** [comment]
@rtholmes Can you add an endpoint to portal that will check credentials before serving the grade reports? I guess at some point the reports will be linked in a frontend view so I'm not sure how you want to handle it. To get a file from the grader service: `FULL_COMMIT_SHA-DELIV_ID/FILENAME`.

**Comment by rtholmes** [comment]
Yes, this is something I can do no problem. If you just add the code to ResultController that I can call into, I can take care of all of the endpoint and authentication pieces.

**Comment by rtholmes** [comment]
Fixed and deployed to 310 and sdmm.
