### ISSUE TITLE
Unable to provision repo D0

### ISSUE THREAD

**Issue by ccunnin8** [ubccpsc/classy#67]
Upon clicking "Provision D0 Repository" the following error message appears: 

"Error provisions d0 repo"

Console:

[Error] <E> 8/18/2018, 4:58:46 PM: SDDM::showError(..) - failure: {"failure":{"message":"Error provisioning d0 repo.","shouldLogout":false}}
	error (portal.js:128)
	showError (portal.js:3769)
	(anonymous function) (portal.js:3587)
	generatorResume
	fulfilled (portal.js:3529)
	promiseReactionJob

Happens in Chrome, Firefox, and Safari 
Multiple users are experiencing this issues

**Comment by ccunnin8** [comment]
Any ETA on this, trying to get started so that I can finish the MicroMasters?

**Comment by rtholmes** [comment]
@ccunnin8 This is now fixed. Thanks for the report (ended up being a git config problem within a docker container which was tricky to debug). 

I'm not sure what this repo is though: https://github.com/SECapstone/secap_ccunnin8 Do you want me to delete it so you can fully provision a working repo?

**Comment by ccunnin8** [comment]
Yes please delete it, it was made when I was trying to provision the repo but it didn’t contain any code.

**Comment by rtholmes** [comment]
Alright, removed. You should be able to provision d0 now if you refresh the webapp.

**Comment by ccunnin8** [comment]
It worked! Thank you!
