### ISSUE TITLE
Provide more flexibility for team & repo naming

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#73]
`repoPrefix` and `teamPrefix` are a good start, but provide mechanism for asking `CourseController` subtypes for full names (if they want to provide one).

e.g., the default repo name will be `repoPrefix_<lowestAvailableNumber>`, but `repoPrefix_uName1-uName2` should be supportable.

**Comment by rtholmes** [comment]
This is done; the `CourseController` extension point gives courses what they need.

**Comment by jopika** [comment]
Current issue with naming teams:
https://github.com/ubccpsc/classy/blob/master/packages/portal/backend/src/controllers/TeamController.ts#L81

Current code allows for duplication of team names (currently very easy as it uses `.length`), which is problematic since teams can not have the same name.

**Comment by rtholmes** [comment]
@jopika Fixed. You'll want to look at this though since this is where you'll specify your team names (this is how 310 does it too, so there's an example there):  https://github.com/ubccpsc/classy/blob/master/packages/portal/backend/src/Factory.ts#L64
