### ISSUE TITLE
.custom properties cannot be null.

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#84]
When using the `.custom` properties on `Deliverable`, `Repository`, and `Team`, the `.custom` should never be set to null. If you are using the property, you should add it explicitly (e.g. `repo.custom.foo = bar`), and deleted explicitly (e.g., `delete repo.custom.foo`). 

You should not just assign something to `.custom` (e.g., `repo.custom = baz`) as this will overwrite any other additions that have been made to the custom property.

It is best practice to prefix any keys with something that is unlikely to conflict with others (e.g., `repo.custom.assignmentRubric` or `repo.custom.sdmmStatus`) rather than names that are more generic (e.g., `repo.custom.obj` or `repo.custom.value`).

**Comment by rtholmes** [comment]
@jopika this is why the 340 tests are all failing right now: `team.custom` is set to `null` in many places.

**Comment by jopika** [comment]
Most recent pushes (02c60530cde3d96cc07ad9ae1fac3040d01725c9) have addressed this issue. Frontend and backend of assignment related methods should be updated in accordance to this change.
