### ISSUE TITLE
Slow Test Override should be in .env file (or somewhere separate)

### ISSUE THREAD

**Issue by jopika** [ubccpsc/classy#85]
Keeping the variable directly inline with the code has the possibility that someone might accidentally commit a modified `override` change, which impacts users.

Ideally, this variable should be placed in a separate file that is easily `.gitignore`-d.

**Comment by jopika** [comment]
@rtholmes Perhaps an .env variable might be a good idea?

**Comment by rtholmes** [comment]
We'll have to see. There is no downside to the flag since the CI system always overrides it and runs all the slow tests anyways.

And I'm currently working on a local running change that gets it from ~11 minutes to ~20 seconds.

**Comment by rtholmes** [comment]
For now we'll mark this as wontfix since #87 solved this enough (for now). We might have to come back to this later though.
