### ISSUE TITLE
Advanced Admin Features

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#92]
- [x] Delete team: Deletes the `Team` AND their GitHub counterparts if they have been provisioned.
- [x] Delete repo: Deletes the `Repository` AND their GitHub counterparts if they have been provisioned.
- [x] Delete Deliverable; deletes the deliv object but NOT any associated teams / repos.
- [x] Manually create team (overriding team size limits)

**Comment by rtholmes** [comment]
@mgelbart all done!

**Comment by mgelbart** [comment]
Great! 🎉
