### ISSUE TITLE
Behaviour for non-group deliverables

### ISSUE THREAD

**Issue by mgelbart** [ubccpsc/classy#94]
When making a deliverable if I do *not* select "Students Make Teams" then, in the student view in portal:

- Current behaviour: the deliverable appears as an option in the dropdown, but team creation is never actually successful (there's an error message)
- Desired behaviour: the deliverable does not appear as an option in the dropdown

**Comment by rtholmes** [comment]
This is already implemented for the default provision/release functionality:

https://github.com/ubccpsc/classy/blob/master/packages/portal/frontend/src/app/views/AdminConfigTab.ts#L99
