### ISSUE TITLE
Team creation page says to enter CWL of partner

### ISSUE THREAD

**Issue by mgelbart** [ubccpsc/classy#98]
I didn't verify this (sorry) but the students are reporting that it says this. It should be ugrad ID. Or maybe just "login" to keep it vague, and the instructor can provide instructions to the students separately.

**Comment by rtholmes** [comment]
this is a 340-specific fix: https://github.com/ubccpsc/classy/blob/master/packages/portal/frontend/html/cs340/student.html#L34

**Comment by rtholmes** [comment]
Will move to fork.
